quickstart/Tiltfile

Pairs with https://github.com/opentdf/backend/pull/144

Update bootstrap chart to 0.4.3

---

.github/workflows/build.yaml

- the `delta` action doesn't work on scheduled runs, since there is no diff.
- so don't run it if on a scheduled run
- Also pulls script check out into its own named job for consistency and runs prettier on the file

🐛 Fix scheduled runs the workflow

---

examples/offline/build-offline-bundle

Cleanup -- these packages are not necessary.

FED-97: Remove unnecessary packages from baseline.

---

examples/webcam-app/package-lock.json
examples/webcam-app/package.json

PLAT-1807
- examples/webcam-app 0.2.0
- npm audit fix --force

webcam-app npm audit fix

---

examples/offline/README.md
examples/offline/build-offline-bundle
examples/offline/docker-load-and-tag-exports
quickstart/Tiltfile
quickstart/start.sh
scripts/pre-reqs
scripts/pre-reqs-linux.sh
scripts/pre-reqs-macos.sh

- Adds a registry service for offline mode
- Adds policy and opa CLI tools to pre-reqs, but you have to request them (they aren't default)
- Updates to renamed `entitlement_store` image

✨ more policy and opa utils

---

examples/abacship-app/Dockerfile
examples/abacship-app/src/components/Board/Board.scss
examples/abacship-app/src/components/Board/Board.tsx

Signed-off-by: obidenko <obidenko@virtru.com>

PLAT-1834 : Abacship UI improvements

---

quickstart/README.md
troubleshooting/README.md

PLAT-1907
- addition of troubleshooting dir and README.md file

Troubleshooting guide

---

CODEOWNERS

formerly https://github.com/opentdf/opentdf/pull/109
weird fork state + signed commits, easier to just delete the other branch and redo this work

PLAT-193; change to tf-created team

---

quickstart/README.md

previously https://github.com/opentdf/opentdf/pull/108
fix broken link and https to http typo.
also added a link to the examples since they are very useful for next steps for a developer.

readme typo and broken link fix, add examples to readme

---

quickstart/Tiltfile
version-tool/Tiltfile

latest kubernetes update deprecated kubectl version --short and tilt has not updated its extension to reflect this

custom min_k8s_version

---

scripts/pre-reqs

- Fixes policy build "expected 3 layers" bug in offline deployment

Bugfux: Bump offline dependency `policy` to latest

---

examples/secure-cycle/README.md
quickstart/helm/values-postgresql.yaml

1.1.0 port of https://github.com/opentdf/opentdf/pull/136

[1.1.0] Add readme and secure cycle dir

---

quickstart/Tiltfile

bump front end chart tag
fixes quickstart and examples ci

Update frontend chart tag

---

examples/Tiltfile
examples/abacship-app/Tiltfile
examples/offline/build-offline-bundle
examples/secure-remote-storage/Tiltfile
examples/web-app/Tiltfile
examples/webcam-app/Tiltfile
openapi/openapi-aggregate.yaml
quickstart/Tiltfile
quickstart/helm/values-keycloak.yaml
quickstart/start.sh

version bumps for opentdf/opentdf. after merging this we can tag main with 1.1.1 .

PLAT-2193; release candidate for opentdf 1.1.1

---

quickstart/start.sh

PLAT-2211
- keycloak-secrets fix

QuickStart uses keycloak-secrets

---

examples/offline/build-offline-bundle
quickstart/Tiltfile
quickstart/start.sh

Update repo link per: https://github.com/bitnami/charts/issues/14029
Due to retention policy change, need to change repo:
```
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
```

Update repo link per: https://github.com/bitnami/charts/issues/14029

---

examples/secure-remote-storage/src/App.js
examples/secure-remote-storage/tests/e2e/App.spec.ts
examples/secure-remote-storage/tests/e2e/helpers/selectors.ts

Playwright tests for Add Store dialog in Secure Storage

---

.github/workflows/traffic.yaml

Forgot to remove line when cleaning up previous PR

Fix error in traffic workflow

---

quickstart/README.md

Added updates defining each of the env vars used for the start script, example commands, and some notes on the start script's behaviors.

PLAT-2212; readme updates for start script args

---

examples/secure-remote-storage/tests/e2e/App.spec.ts
examples/secure-remote-storage/tests/e2e/helpers/selectors.ts

Cases:
- errors handling
- empty state of the Save Store dialog
- tooltip
PLAT-2293

More Playwright tests for Secure Remote Storage

---

.github/workflows/secure-remote-storage-playwright-test.yaml
examples/secure-remote-storage/tests/e2e/App.spec.ts

Add hosts to /etc/hosts for Secure Storage integration setup 

---

examples/helm/values-bootstrap.yaml
quickstart/helm/values-keycloak-bootstrap.yaml

closes https://github.com/opentdf/opentdf/issues/261

Quickstart Remove clients in master realm

---

examples/abacship-app/package-lock.json
examples/abacship-app/package.json
examples/secure-remote-storage/package-lock.json
examples/todo-react/package-lock.json
examples/webcam-app/package-lock.json

- updates axios
- other dependabot fixes

examples npm audio fix

---

.github/workflows/aggregate-openapi.yaml

Pipeline to update aggregate openapi
Take tag/branch of backend to use as input
Makes PR with changes

PLAT-3022 Add pipeine to update aggregate openapi

---

.github/workflows/build.yaml
chartsVersions.json
quickstart/helm/values-keycloak.yaml
quickstart/start.sh

Upgrade to opentdf 1.6.0
